# Running BERTScore on Cocosum dev and test data

In [ ]:
import numpy as np
import pandas as pd
import torch
import json

In [ ]:
!pip install evaluate
!pip install bert_score

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.4/81.4 KB 3.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 12.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 24.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.0/132.0 KB 18.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.0/213.0 KB 21.2 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 KB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 52.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 100.6 MB/s eta 0:00:00


In [ ]:
with open('dev.json', 'r') as j:
     dev = json.loads(j.read())

with open('test.json', 'r') as k:
     test = json.loads(k.read())

In [ ]:
print(dev)
print(len(dev))

[{'entity_a': '254461', 'entity_b': '185747', 'entity_a_summary': ['The hotel has conference rooms available to rent out for conferences and corporate events. The location of this hotel makes it easy to access restaurants, the river and shops. The rooms are a good size and well decorated. The bathroom in the hotel was large and with a large bathtub. Small touches like a chocolate on the pillow are also nice. The hotel has a roof terrace for drinks. Unfortunately the hotel is missing the availability of a pool.', "This is a lovely place that was wonderful in all ways. It is definitely a place you will want to return again. The hotel is in walking condition to local restaurants, bars and even the Mont Royal. Beautifully decorated hotel rooms that are well designed and comfortable for all occasions. Very spacious in size with luxurious amenities in the bathroom, and it's the little touches such as chocolates on the pillow that make these rooms even more memorable. The hotel features some 

In [ ]:
print(test)
print(len(test))

[{'entity_a': '296582', 'entity_b': '294609', 'entity_a_summary': ['The hotel is decent and a great choice if looking for a cheap, clean, and secure place to stay. The hotel is close to the Grand Bazaar, Blue Mosque and the tram lines for transport around the city. The rooms are pretty comfortable but this room in particularly constantly had smoke blowing up from the lobby. The staff at the hotel provided a good service. The hotel had breakfast included in the price of the stay. One thing to note with the hotel is that there is only a one way transfer, so you will have to pay for either the pick up or the drop off to the airport.', "The hotel is cheap, clean and has good security. This hotel is situated in a really convenient location for those who wish to see some of the grand sites this place has to offer, whether it's the bazaar or religious sites. The rooms in the hotel are comfortable, although cigarette fumes often drifted into the surrounding rooms. The staff will provide a real

In [ ]:
dev[0]

{'entity_a': '254461',
 'entity_b': '185747',
 'entity_a_summary': ['The hotel has conference rooms available to rent out for conferences and corporate events. The location of this hotel makes it easy to access restaurants, the river and shops. The rooms are a good size and well decorated. The bathroom in the hotel was large and with a large bathtub. Small touches like a chocolate on the pillow are also nice. The hotel has a roof terrace for drinks. Unfortunately the hotel is missing the availability of a pool.',
  "This is a lovely place that was wonderful in all ways. It is definitely a place you will want to return again. The hotel is in walking condition to local restaurants, bars and even the Mont Royal. Beautifully decorated hotel rooms that are well designed and comfortable for all occasions. Very spacious in size with luxurious amenities in the bathroom, and it's the little touches such as chocolates on the pillow that make these rooms even more memorable. The hotel features so

In [ ]:
import bert_score

In [ ]:
SCORER = bert_score.BERTScorer(model_type="microsoft/deberta-xlarge-mnli", lang="en", rescale_with_baseline=True)

Some weights of the model checkpoint at microsoft/deberta-xlarge-mnli were not used when initializing DebertaModel: ['pooler.dense.bias', 'classifier.bias', 'pooler.dense.weight', 'classifier.weight']
- This IS expected if you are initializing DebertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


first column: precision

second column: recall

third column: f1 score

In [ ]:
scores = SCORER.score([dev[0]['entity_b_summary'][0]],[dev[0]['entity_b_summary'][1]])
print(scores)

(tensor([0.2437]), tensor([0.2230]), tensor([0.2364]))


In [ ]:
for i in dev:

  matrix = []

  for j in range(len(i['entity_a_summary'])-1):

    scores = SCORER.score([i['entity_a_summary'][j]], [i['entity_a_summary'][j+1]])

    print(scores)


(tensor([0.4175]), tensor([0.2840]), tensor([0.3502]))
(tensor([0.3138]), tensor([0.3323]), tensor([0.3257]))
(tensor([0.5898]), tensor([0.5222]), tensor([0.5571]))
(tensor([0.5183]), tensor([0.5108]), tensor([0.5165]))
(tensor([0.4317]), tensor([0.3926]), tensor([0.4143]))
(tensor([0.4098]), tensor([0.3753]), tensor([0.3948]))
(tensor([0.3855]), tensor([0.4234]), tensor([0.4066]))
(tensor([0.3847]), tensor([0.3046]), tensor([0.3462]))
(tensor([0.3911]), tensor([0.4728]), tensor([0.4331]))
(tensor([0.4423]), tensor([0.5364]), tensor([0.4900]))
(tensor([0.4264]), tensor([0.3945]), tensor([0.4127]))
(tensor([0.4180]), tensor([0.3716]), tensor([0.3969]))
(tensor([0.3484]), tensor([0.3008]), tensor([0.3269]))
(tensor([0.3388]), tensor([0.3664]), tensor([0.3551]))
(tensor([0.5218]), tensor([0.4331]), tensor([0.4783]))
(tensor([0.4069]), tensor([0.4066]), tensor([0.4091]))
(tensor([0.4566]), tensor([0.3639]), tensor([0.4112]))
(tensor([0.2052]), tensor([0.3666]), tensor([0.2840]))
(tensor([0

In [ ]:
for i in dev:

  matrix = []

  for j in range(len(i['entity_a_summary'])-1):

    scores = SCORER.score([i['entity_b_summary'][j]], [i['entity_b_summary'][j+1]])

    print(scores)

(tensor([0.2437]), tensor([0.2230]), tensor([0.2364]))
(tensor([0.3017]), tensor([0.2887]), tensor([0.2980]))
(tensor([0.3269]), tensor([0.3137]), tensor([0.3230]))
(tensor([0.3022]), tensor([0.2845]), tensor([0.2961]))
(tensor([0.3834]), tensor([0.2915]), tensor([0.3387]))
(tensor([0.2810]), tensor([0.3596]), tensor([0.3219]))
(tensor([0.2742]), tensor([0.3199]), tensor([0.2995]))
(tensor([0.4158]), tensor([0.4256]), tensor([0.4230]))
(tensor([0.4079]), tensor([0.3416]), tensor([0.3765]))
(tensor([0.3479]), tensor([0.3212]), tensor([0.3371]))
(tensor([0.5234]), tensor([0.5482]), tensor([0.5376]))
(tensor([0.5782]), tensor([0.5433]), tensor([0.5623]))
(tensor([0.3938]), tensor([0.3557]), tensor([0.3770]))
(tensor([0.3413]), tensor([0.3207]), tensor([0.3336]))
(tensor([0.3837]), tensor([0.4094]), tensor([0.3989]))
(tensor([0.4313]), tensor([0.4313]), tensor([0.4336]))
(tensor([0.4181]), tensor([0.3135]), tensor([0.3664]))
(tensor([0.3336]), tensor([0.3274]), tensor([0.3332]))
(tensor([0

# Dev BERTscore on contrastive summaries

In [ ]:
matrix = []

for i in dev:

  ent_a = [" ".join(i['entity_a_summary'])]
  ent_b = [" ". join(i['entity_b_summary'])]

  scores = SCORER.score(ent_a, ent_b)

  matrix.append([i.detach().numpy()[0] for i in scores])

  print(scores)

print('\n')
print(np.mean(matrix, axis = 0))

(tensor([0.1910]), tensor([0.2082]), tensor([0.2027]))
(tensor([0.2375]), tensor([0.1339]), tensor([0.1869]))
(tensor([0.2278]), tensor([0.2232]), tensor([0.2286]))
(tensor([0.2206]), tensor([0.2175]), tensor([0.2222]))
(tensor([0.2464]), tensor([0.2384]), tensor([0.2454]))
(tensor([0.2393]), tensor([0.2990]), tensor([0.2714]))
(tensor([0.1593]), tensor([0.1758]), tensor([0.1708]))
(tensor([0.2956]), tensor([0.2545]), tensor([0.2776]))
(tensor([0.2376]), tensor([0.1571]), tensor([0.1993]))
(tensor([0.2258]), tensor([0.2503]), tensor([0.2410]))


[0.22808082 0.21577902 0.2245957 ]


In [ ]:
total = []

for i in dev:

  matrix = []

  for j in range(len(i['entity_a_summary'])):

    scores = SCORER.score([i['entity_a_summary'][j]], [i['entity_b_summary'][j]])

    # print([i.detach().numpy()[0] for i in scores])

    matrix.append([i.detach().numpy()[0] for i in scores])

  print(np.mean(matrix, axis = 0))

  total.append(np.mean(matrix, axis = 0))

print('\n')
print(np.mean(total, axis = 0))


[0.22584058 0.22435777 0.22738032]
[0.32790336 0.24727774 0.28920972]
[0.2491021  0.24407077 0.24949266]
[0.24724782 0.25372034 0.25266013]
[0.288537   0.26173154 0.2764436 ]
[0.25386858 0.3159006  0.28692687]
[0.20055248 0.22011745 0.21340156]
[0.34415212 0.29303244 0.32051143]
[0.3144218  0.2419573  0.27921635]
[0.23526616 0.2811431  0.26052746]


[0.26868922 0.2583309  0.265577  ]


# Dev BERTScore on contrastive and common summaries

In [ ]:
matrix = []

for i in dev:

  ent_a = [" ".join(i['entity_a_summary'])]
  comm = [" ". join(i['common_summary'])]

  scores = SCORER.score(ent_a, comm)

  matrix.append([i.detach().numpy()[0] for i in scores])

  print(scores)

print('\n')
print(np.mean(matrix, axis = 0))


(tensor([0.0185]), tensor([0.3160]), tensor([0.1527]))
(tensor([0.1208]), tensor([0.1668]), tensor([0.1468]))
(tensor([-0.0991]), tensor([0.1991]), tensor([0.0340]))
(tensor([0.0567]), tensor([0.2388]), tensor([0.1444]))
(tensor([0.0756]), tensor([0.3390]), tensor([0.1969]))
(tensor([0.1624]), tensor([0.3890]), tensor([0.2691]))
(tensor([-0.0144]), tensor([0.1925]), tensor([0.0835]))
(tensor([-0.0797]), tensor([0.2819]), tensor([0.0768]))
(tensor([0.1293]), tensor([0.2220]), tensor([0.1772]))
(tensor([-0.0071]), tensor([0.2205]), tensor([0.0993]))


[0.0363     0.25656748 0.13808215]


In [ ]:
total = []

for i in dev:

  matrix = []

  for j in range(len(i['entity_a_summary'])):

    scores = SCORER.score([i['entity_a_summary'][j]], [i['common_summary'][j]])

    # print([i.detach().numpy()[0] for i in scores])

    matrix.append([i.detach().numpy()[0] for i in scores])

  print(np.mean(matrix, axis = 0))

  total.append(np.mean(matrix, axis = 0))

print('\n')
print(np.mean(total, axis = 0))


[0.08670902 0.44160867 0.2430046 ]
[0.22087598 0.24860348 0.23763166]
[0.03465864 0.42027164 0.20131934]
[0.09991661 0.34383142 0.21125372]
[0.1183707  0.4310118  0.25943246]
[0.21233265 0.46943477 0.33173963]
[0.09489763 0.35610405 0.21544631]
[0.04836041 0.39026454 0.1988622 ]
[0.2060671  0.28721383 0.24772048]
[0.08355713 0.36677337 0.21237384]


[0.12057459 0.37551177 0.23587842]


In [ ]:
matrix = []

for i in dev:

  ent_b = [" ".join(i['entity_b_summary'])]
  comm = [" ". join(i['common_summary'])]

  scores = SCORER.score(ent_b, comm)

  matrix.append([i.detach().numpy()[0] for i in scores])

  print(scores)

print('\n')
print(np.mean(matrix, axis = 0))


(tensor([-0.0153]), tensor([0.2761]), tensor([0.1162]))
(tensor([0.0635]), tensor([0.1798]), tensor([0.1224]))
(tensor([-0.0522]), tensor([0.2693]), tensor([0.0903]))
(tensor([0.0642]), tensor([0.2646]), tensor([0.1596]))
(tensor([-0.0132]), tensor([0.2790]), tensor([0.1186]))
(tensor([0.2135]), tensor([0.3873]), tensor([0.2977]))
(tensor([0.0587]), tensor([0.2868]), tensor([0.1656]))
(tensor([-0.0972]), tensor([0.2128]), tensor([0.0404]))
(tensor([0.1035]), tensor([0.2978]), tensor([0.1964]))
(tensor([0.0115]), tensor([0.1994]), tensor([0.1016]))


[0.03371315 0.2652931  0.1408825 ]


In [ ]:
total = []

for i in dev:

  matrix = []

  for j in range(len(i['entity_b_summary'])):

    scores = SCORER.score([i['entity_b_summary'][j]], [i['common_summary'][j]])

    matrix.append([i.detach().numpy()[0] for i in scores])

  print(np.mean(matrix, axis = 0))

  total.append(np.mean(matrix, axis = 0))

print('\n')
print(np.mean(total, axis = 0))

[0.05969964 0.35059762 0.19050808]
[0.15674217 0.2675501  0.21285327]
[0.07549372 0.5072181  0.2599982 ]
[0.15160638 0.40778878 0.26975062]
[0.0528021  0.34465727 0.18339439]
[0.25067356 0.4542259  0.34768823]
[0.15285839 0.41690525 0.27447072]
[0.02123119 0.41383573 0.19019705]
[0.191275   0.37345123 0.27774474]
[0.10493366 0.35554162 0.22126438]


[0.12173158 0.38917717 0.24278696]


#Test BERTScore on contrastive summaries

In [ ]:
matrix = []

for i in test:

  ent_a = [" ".join(i['entity_a_summary'])]
  ent_b = [" ". join(i['entity_b_summary'])]

  scores = SCORER.score(ent_a, ent_b)
  matrix.append([i.detach().numpy()[0] for i in scores])

  print(scores)

print('\n')
print(np.mean(matrix, axis = 0))

(tensor([0.2690]), tensor([0.2404]), tensor([0.2576]))
(tensor([0.2065]), tensor([0.2476]), tensor([0.2298]))
(tensor([0.2591]), tensor([0.2397]), tensor([0.2523]))
(tensor([0.2316]), tensor([0.2202]), tensor([0.2290]))
(tensor([0.1972]), tensor([0.1312]), tensor([0.1667]))
(tensor([0.2349]), tensor([0.2236]), tensor([0.2323]))
(tensor([0.2594]), tensor([0.2242]), tensor([0.2446]))
(tensor([0.2319]), tensor([0.2365]), tensor([0.2373]))
(tensor([0.2031]), tensor([0.2697]), tensor([0.2386]))
(tensor([0.2905]), tensor([0.2454]), tensor([0.2705]))
(tensor([0.2180]), tensor([0.2374]), tensor([0.2307]))
(tensor([0.2088]), tensor([0.1974]), tensor([0.2063]))
(tensor([0.1936]), tensor([0.2185]), tensor([0.2091]))
(tensor([0.2844]), tensor([0.2000]), tensor([0.2439]))
(tensor([0.2322]), tensor([0.2626]), tensor([0.2503]))
(tensor([0.1970]), tensor([0.2292]), tensor([0.2160]))
(tensor([0.2471]), tensor([0.2203]), tensor([0.2366]))
(tensor([0.2645]), tensor([0.2555]), tensor([0.2630]))


[0.23493

In [ ]:
total = []

for i in test:

  matrix = []

  for j in range(len(i['entity_a_summary'])):

    scores = SCORER.score([i['entity_a_summary'][j]], [i['entity_b_summary'][j]])

    # print([i.detach().numpy()[0] for i in scores])

    matrix.append([i.detach().numpy()[0] for i in scores])

  print(np.mean(matrix, axis = 0))

  total.append(np.mean(matrix, axis = 0))

print('\n')
print(np.mean(total, axis = 0))


[0.2994331  0.29057434 0.29695532]
[0.22842397 0.32763448 0.2783643 ]
[0.28987142 0.2750453  0.28527793]
[0.22617643 0.24031554 0.23580773]
[0.20132548 0.16603999 0.18574071]
[0.2542734  0.25195315 0.2559809 ]
[0.28450596 0.25478828 0.2722931 ]
[0.253826   0.24112563 0.24993479]
[0.20231552 0.27263162 0.23956156]
[0.32528967 0.2731913  0.300331  ]
[0.23101223 0.27146053 0.25390926]
[0.26353323 0.22689004 0.24782239]
[0.23776382 0.3203238  0.2805014 ]
[0.31828275 0.25197896 0.28657106]
[0.25125757 0.32595226 0.2898148 ]
[0.24382973 0.26654756 0.25790855]
[0.26357016 0.25563022 0.26252148]
[0.3093826  0.27602792 0.29488304]


[0.2602263  0.26600614 0.26523218]


# Test BERTScore on contrastive and commmon

In [ ]:
matrix = []

for i in test:

  ent_a = [" ".join(i['entity_a_summary'])]
  comm = [" ". join(i['common_summary'])]

  scores = SCORER.score(ent_a, comm)
  matrix.append([i.detach().numpy()[0] for i in scores])

  print(scores)

print('\n')
print(np.mean(matrix, axis = 0))

(tensor([0.0448]), tensor([0.2717]), tensor([0.1511]))
(tensor([-0.2079]), tensor([0.1328]), tensor([-0.0615]))
(tensor([0.0665]), tensor([0.3248]), tensor([0.1857]))
(tensor([-0.1460]), tensor([0.1651]), tensor([-0.0089]))
(tensor([0.1471]), tensor([0.2656]), tensor([0.2068]))
(tensor([-0.3043]), tensor([0.2543]), tensor([-0.0954]))
(tensor([-0.1673]), tensor([0.1901]), tensor([-0.0141]))
(tensor([-0.0972]), tensor([0.1615]), tensor([0.0209]))
(tensor([-0.0702]), tensor([0.2195]), tensor([0.0600]))
(tensor([0.1446]), tensor([0.2121]), tensor([0.1807]))
(tensor([0.0426]), tensor([0.2695]), tensor([0.1489]))
(tensor([-0.0134]), tensor([0.2799]), tensor([0.1189]))
(tensor([-0.1512]), tensor([0.1071]), tensor([-0.0338]))
(tensor([0.0529]), tensor([0.2872]), tensor([0.1624]))
(tensor([-0.1544]), tensor([0.2817]), tensor([0.0256]))
(tensor([-0.0415]), tensor([0.3065]), tensor([0.1109]))
(tensor([-0.2287]), tensor([0.1468]), tensor([-0.0709]))
(tensor([-0.0627]), tensor([0.3906]), tensor([0.

In [ ]:
total = []

for i in test:

  matrix = []

  for j in range(len(i['entity_a_summary'])):

    scores = SCORER.score([i['entity_a_summary'][j]], [i['common_summary'][j]])

    matrix.append([i.detach().numpy()[0] for i in scores])

  print(np.mean(matrix, axis = 0))

  total.append(np.mean(matrix, axis = 0))

print('\n')
print(np.mean(total, axis = 0))

[0.133578  0.4495139 0.2747922]
[-0.07920736  0.31972095  0.09011476]
[0.1750408  0.49649915 0.31992117]
[-0.01509001  0.33719334  0.1391796 ]
[0.18764438 0.34185052 0.26160356]
[-0.18181801  0.44061065  0.05102593]
[-0.03726581  0.36425635  0.13348338]
[0.04568987 0.34426513 0.1801117 ]
[0.00420204 0.44122064 0.18795805]
[0.17985605 0.27024698 0.22646487]
[0.0892334  0.36382428 0.21439451]
[0.08422249 0.43627986 0.2394542 ]
[-0.07477324  0.27682337  0.07823265]
[0.12445273 0.48341975 0.28128454]
[-0.03856296  0.38580725  0.14073132]
[0.05935545 0.46674895 0.23394334]
[-0.08776325  0.32103518  0.08432252]
[0.03075231 0.51499796 0.23223068]


[0.03330816 0.39190638 0.18718049]


In [ ]:
matrix = []

for i in test:

  ent_b = [" ".join(i['entity_b_summary'])]
  comm = [" ". join(i['common_summary'])]

  scores = SCORER.score(ent_b, comm)
  matrix.append([i.detach().numpy()[0] for i in scores])

  print(scores)

print('\n')
print(np.mean(matrix, axis = 0))

(tensor([0.0346]), tensor([0.3382]), tensor([0.1713]))
(tensor([-0.1417]), tensor([0.1703]), tensor([-0.0042]))
(tensor([0.0198]), tensor([0.3114]), tensor([0.1518]))
(tensor([-0.1193]), tensor([0.2267]), tensor([0.0310]))
(tensor([0.0527]), tensor([0.2152]), tensor([0.1319]))
(tensor([-0.2969]), tensor([0.0796]), tensor([-0.1410]))
(tensor([-0.2012]), tensor([0.2000]), tensor([-0.0341]))
(tensor([-0.0517]), tensor([0.2066]), tensor([0.0666]))
(tensor([0.0505]), tensor([0.3270]), tensor([0.1768]))
(tensor([0.1441]), tensor([0.2703]), tensor([0.2073]))
(tensor([0.0561]), tensor([0.2601]), tensor([0.1530]))
(tensor([-0.0308]), tensor([0.2723]), tensor([0.1050]))
(tensor([-0.1224]), tensor([0.1197]), tensor([-0.0110]))
(tensor([-0.0144]), tensor([0.2789]), tensor([0.1179]))
(tensor([-0.0647]), tensor([0.2693]), tensor([0.0822]))
(tensor([0.0047]), tensor([0.2722]), tensor([0.1272]))
(tensor([-0.2275]), tensor([0.1935]), tensor([-0.0549]))
(tensor([-0.1557]), tensor([0.2964]), tensor([0.02

In [ ]:
total = []

for i in test:

  matrix = []

  for j in range(len(i['entity_b_summary'])):

    scores = SCORER.score([i['entity_b_summary'][j]], [i['common_summary'][j]])

    matrix.append([i.detach().numpy()[0] for i in scores])

  print(np.mean(matrix, axis = 0))

  total.append(np.mean(matrix, axis = 0))

print('\n')
print(np.mean(total, axis = 0))

[0.14609236 0.49030957 0.2992694 ]
[0.01670466 0.39379275 0.17970274]
[0.13882138 0.4707928  0.28743494]
[-0.00474281  0.39072275  0.16510369]
[0.12656295 0.2636046  0.19452198]
[-0.17774057  0.3078008   0.01535079]
[-0.04711453  0.4643116   0.15938051]
[0.06888772 0.3544548  0.19781451]
[0.11718401 0.52521604 0.29296872]
[0.17151116 0.29632172 0.23313256]
[0.14960913 0.36036694 0.24952114]
[0.07376062 0.40704992 0.2222455 ]
[-0.02808152  0.2662405   0.10416243]
[0.06380589 0.45666942 0.22961998]
[0.03846977 0.4000272  0.1958168 ]
[0.0963643  0.5133232  0.27401266]
[-0.09545127  0.34210345  0.08631491]
[-0.01921845  0.46820998  0.1807934 ]


[0.04641249 0.39840657 0.1981759 ]


In [ ]:
from bert_score import plot_example


plot_example(dev[0]['entity_b_summary'][0],dev[0]['entity_b_summary'][1], model_type="microsoft/deberta-xlarge-mnli",rescale_with_baseline = True, lang="en")